spring:
  # MQ
  rabbitmq:
    host: 47.115.19.227
    port: 5672
    virtual-host: /
    # 开启消费端手动 ack机制
    listener:
      simple:
        acknowledge-mode: manual
    # 开启发送端确认
    publisher-confirm-type: correlated
    # 开启发送端消息抵达队列确认
    publisher-returns: true
    # 抵达队列，以异步发送优先回调returnCallback
    template:
      mandatory: true

  task:
    execution:
      pool:
        core-size: 5
        max-size: 50
#        scheduling:
#          pool:
#            size: 5
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/

  redis:
    host: 47.115.19.227
    port: 6379
    password: 123456
    timeout: 200000
  session:
    store-type: redis

logging:
  level:
    com.desen.desenmall: debug
server:
  port: 25000
  # 后台session在redis的过期时间
  servlet:
    session:
      timeout: 30m




