logging:
  level:
    com.desen.desenmall: debug
server:
  port: 30000

spring:
  cloud:
    alicloud:
      access-key: LTAI5t99RuZJ71wXaQ1axZq8Q
      secret-key: 6lCHST0wWz3vZaiGcU4G6SZxS1Ose3R
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: desenmall-product
