spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.115.19.227:3307/desenmall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto


logging:
  level:
    com.desen.desenmall: debug
server:
  port: 7000
